#!/bin/bash
# This script creates a user account under macOS
# Adapted from https://gist.github.com/jhbush/3087016

USERNAME=$1

if [[ -z "$USERNAME" ]]; then
  echo "Error removing user: No username specified"
  exit 1
fi

# Ensure running as root
if [[ $UID -ne 0 ]]; then echo "$0 requires root."; exit 1; fi

if ! [[ -d /var/lufoodwatch/.home ]]; then
  echo "Home directory missing, creating now..."
  mkdir /var/lufoodwatch/.home
fi

USERID=$(id -u $USERNAME)
if [[ $? -eq 0 ]]; then
  echo "User $USERNAME already exists with id $USERID, skipping..."
else
  # Create user and group
  useradd -d /var/lufoodwatch/.home -s /bin/bash -r $USERNAME
  
  USERID=$(id -u $USERNAME)
  echo "Created user #$USERID: $USERNAME"
fi