#!/bin/bash
# This script creates a user account under macOS
# Adapted from https://gist.github.com/jhbush/3087016

# === Typically, this is all you need to edit ===

USERNAME=$1

if [[ -z "$USERNAME" ]]; then
  echo "Error removing user: No username specified"
  exit 1
fi

# ====

# Ensure running as root
if [[ $UID -ne 0 ]]; then echo "$0 requires root."; exit 1; fi

USERID=$(id -u $USERNAME)
if [[ $? -eq 0 ]]; then
  echo "User $USERNAME already exists with id $USERID, skipping..."
else
  # Create user and group
  useradd -d /var/lufoodwatch -s /sbin/nologin -r $USERNAME
  
  # Set ownership of the home directory
  chown "$USERNAME:$USERNAME" /var/lufoodwatch
  # Remove write permissions for all files in (and including) the home directory
  chmod -R ugo-w /var/lufoodwatch
  
  USERID=$(id -u $USERNAME)
  echo "Created user #$USERID: $USERNAME"
fi