#!/bin/bash
# This script creates a user account under macOS
# Adapted from https://gist.github.com/jhbush/3087016

USERNAME=$1

if [[ -z "$USERNAME" ]]; then
  echo "Error removing user: No username specified"
  exit 1
fi

# Ensure running as root
if [[ $UID -ne 0 ]]; then echo "$0 requires root."; exit 1; fi

_GROUP=$(dscl . -read "/Groups/$USERNAME" PrimaryGroupID 2>/dev/null)
if [[ $? -eq 0 ]]; then
  GROUPID=$(echo "$_GROUP" | awk '{print $2}')
  echo "Group $USERNAME already exists with id $GROUPID, skipping..."
else
  # Find out the next available group ID
  MAXID=$(dscl . -list /Groups PrimaryGroupID | awk '{print $2}' | sort -ug | tail -1)
  GROUPID=$((MAXID+1))

  # Create group
  dscl . -create "/Groups/$USERNAME"
  dscl . -create "/Groups/$USERNAME" PrimaryGroupID "$GROUPID"
  
  echo "Created group #$GROUPID: $USERNAME"
fi


_USER=$(dscl . -read "/Users/$USERNAME" UniqueID 2>/dev/null)
if [[ $? -eq 0 ]]; then
  USERID=$(echo "$_USER" | awk '{print $2}')
  echo "User $USERNAME already exists with id $USERID, skipping..."
else
  # Find out the next available user ID
  MAXID=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -ug | tail -1)
  USERID=$((MAXID+1))
  
  mkdir /var/lufoodwatch/.home
  
  # Create the user account
  dscl . -create "/Users/$USERNAME"
  dscl . -create "/Users/$USERNAME" UserShell /bin/bash
  dscl . -create "/Users/$USERNAME" UniqueID "$USERID"
  dscl . -create "/Users/$USERNAME" PrimaryGroupID "$GROUPID"
  dscl . -create "/Users/$USERNAME" NFSHomeDirectory /private/var/lufoodwatch/.home  # /var is a symlink to /private/var on macOS
  dscl . -create "/Users/$USERNAME" IsHidden 1
  
  echo "Created user #$USERID: $USERNAME"
fi