#!/bin/bash

set -e

# Ensure running as root
if [[ $UID -ne 0 ]]; then echo "$0 requires root."; exit 1; fi

# 'cd' to containing directory
cd -P -- "$(dirname -- "$0")"

USERNAME="$1"

unamestr=$(uname)
if [[ "$unamestr" == "Darwin" ]]; then
  chmod +x ./createuser_mac
  ./createuser_mac "$USERNAME"
elif [[ "$unamestr" == "Linux" ]]; then
  chmod +x ./createuser_linux
  ./createuser_linux "$USERNAME"
else
  echo "Unsupported OS '$unamestr'"
  exit 1
fi

echo "$USERNAME" > ../../.username
chown "$USERNAME:$USERNAME" ../../.username