#!/bin/bash

USERNAME=$1

# Ensure running as root
if [[ $UID -ne 0 ]]; then echo "$0 requires root."; exit 1; fi

cd /var/lufoodwatch/cli

echo "Compiling binary..."
# Compile binary (this is required so the setuid bit works)
mkdir bin
gcc binary.c -o bin/lufoodwatchserver


echo -n "Setting ownership & permissions..."
# Set script owner
chown "$USERNAME:$USERNAME" /var/lufoodwatch/cli/script
# Set script permissions (owner [read/exec] + group/other [-nothing-])
chmod 500 /var/lufoodwatch/cli/script

# Set owner of 'bin' folder and contents
chown -R "$USERNAME:$USERNAME" /var/lufoodwatch/cli/bin
# Set 'bin' permissions (owner/group/other [read/execute])
chmod 555 /var/lufoodwatch/cli/bin
# Set binary permissions (setuid + owner/group/other [read/write])
chmod 4555 /var/lufoodwatch/cli/bin/lufoodwatchserver
echo "done"


echo -n "Linking into /usr/local/bin/... "
# Create symlink
ln -s /var/lufoodwatch/cli/bin/lufoodwatchserver /usr/local/bin/lufoodwatchserver
echo "done"