#!/bin/bash
# This script creates a user account under macOS
# Adapted from https://gist.github.com/jhbush/3087016

# === Typically, this is all you need to edit ===

USERNAME=$1
GROUPNAME=$2

# ====

# Ensure running as root
if [[ $UID -ne 0 ]]; then echo "Please run $0 as root." && exit 1; fi

dscl . -read /Groups/$GROUPNAME > /dev/null 2>&1
if [[ $? -eq 0 ]]; then
  GROUPID=$(dscl . -read /Groups/$GROUPNAME PrimaryGroupID | awk '{print $2}')
  echo "Group $GROUPNAME already exists with id $GROUPID, skipping..."
else
  # Find out the next available group ID
  MAXID=$(dscl . -list /Groups PrimaryGroupID | awk '{print $2}' | sort -ug | tail -1)
  GROUPID=$((MAXID+1))

  # Create group
  dscl . -create /Groups/$GROUPNAME
  dscl . -create /Groups/$GROUPNAME PrimaryGroupID "$GROUPID"
  
  echo "Created group #$GROUPID: $GROUPNAME"
fi


dscl . -read /Users/$USERNAME > /dev/null 2>&1
if [[ $? -eq 0 ]]; then
  USERID=$(dscl . -read /Users/$USERNAME UniqueID | awk '{print $2}')
  echo "User $USERNAME already exists with id $USERID, skipping..."
else
  # Find out the next available user ID
  MAXID=$(dscl . -list /Users UniqueID | awk '{print $2}' | sort -ug | tail -1)
  USERID=$((MAXID+1))
  
  # Create the user account
  dscl . -create /Users/$USERNAME
  dscl . -create /Users/$USERNAME UserShell /bin/bash
  dscl . -create /Users/$USERNAME UniqueID "$USERID"
  dscl . -create /Users/$USERNAME PrimaryGroupID "$GROUPID"
  
  echo "Created user #$USERID: $USERNAME"
fi