#!/bin/bash

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

# 'cd' to containing directory
cd -P -- "$(dirname -- "$0")"

# Install node (if needed)

# Install crontab
node install_crontab.js